<?php
// $Id: simpleseo.module,v 1.3.2.0 2011/04/20 8:31:00 ourwayoflife Exp $

function simpleseo_form_node_form_alter(&$form, $form_state) {
  $nid = $form['nid']['#value'];
   
  $title = '';
  $description = '';
  $keywords = '';
  
  if ($nid) {
    $metaData = simpleseo_get_meta_data($nid);
    if ($metaData) {
      $title = $metaData->title;
      $description = $metaData->description;
      $keywords = explode(', ', $metaData->keywords);
      $keywords = implode("\r\n", $keywords);
    }
  }
  
  $form['simpleseo'] = array(
    '#type' => 'fieldset',
    '#title' => t('SimpleSEO settings'),
    '#access' => user_access('administer menu'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#tree' => TRUE,
    '#weight' => -2,
    '#attributes' => array('class' => array('menu-link-form')),
  );
  $form['simpleseo']['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#description' => 'Enter the search engine friendly title of this post.',
    '#default_value' => $title    
  );
  $form['simpleseo']['description'] = array(
    '#type' => 'textarea',    
    '#title' => t('Description'),
    '#description' => 'Enter the meta description of this post.',
    '#default_value' => $description        
  );
  $form['simpleseo']['keywords'] = array(
    '#type' => 'textarea',    
    '#title' => t('Keywords'),
    '#description' => 'Enter the meta keywords of this post. Each line represents a single keyword.',
    '#default_value' => $keywords    
  );    
}

function simpleseo_preprocess_html(&$variables) {  
  $node = menu_get_object();
  
  if ($node) {  
    $metaData = simpleseo_get_meta_data($node->nid);    
    if ($metaData->title) {
      $variables['head_title'] = $metaData->title . ' | ' . $variables['head_title_array']['name'];
    }  
  }
}

function simpleseo_get_meta_data($nid) { 
  $selectMetaData = db_select('simpleseo', 's');
  $selectMetaData->fields('s');
  $selectMetaData->condition('s.nid', $nid);
  $metaData = $selectMetaData->execute()->fetch();
  
  if ($metaData) {
    return $metaData; 
  }
  else {
    return false;
  }
}

function simpleseo_node_insert($node) {
  $nid = $node->nid;
    
  $data = simpleseo_get_node_object_meta_data($node);

  //only handle node insert operations
  if ($data['title'] || $data['description'] || $data['keywords']) { 
    simpleseo_insert_meta_data($nid, $data);
  }  
}

function simpleseo_node_presave($node) { 
  $nid = $node->nid;
  
  $data = simpleseo_get_node_object_meta_data($node);
    
  //only handle node update operations
  if (!$node->is_new) {
    if ($data['title'] || $data['description'] || $data['keywords']) { 
      if (simpleseo_get_meta_data($nid)) { 
        simpleseo_update_meta_data($nid, $data);
      }
      else {
        simpleseo_insert_meta_data($nid, $data);
      }
    }
    //if all fields are not specified during this update, delete
    //the meta data record from the database for cleaning purposes
    else {
      simpleseo_delete_meta_data($nid);
    }
  }
}

function simpleseo_delete_meta_data($nid) {
  $query = db_delete('simpleseo');
  $query->condition('nid', $nid);
  $query->execute();  
}

function simpleseo_update_meta_data($nid, $data) {
  $updateMetaData = db_update('simpleseo'); 
  $updateMetaData->fields(array(
    'title' => $data['title'], 
    'description' => $data['description'],
    'keywords' => $data['keywords']));
  $updateMetaData->condition('nid', $nid);
  $updateMetaData->execute();   
}

function simpleseo_insert_meta_data($nid, $data) {
  $insertMetaData = db_insert('simpleseo');
  $insertMetaData->fields(array(
    'nid' => $nid, 
    'title' => $data['title'], 
    'description' => $data['description'],
    'keywords' => $data['keywords']));  
  $insertMetaData->execute();  
}

function simpleseo_get_node_object_meta_data($node) {
  $data = array();
  
  $data['title'] = trim($node->simpleseo['title']);
  $data['description'] = trim($node->simpleseo['description']);
  $keywords = explode("\r\n", trim($node->simpleseo['keywords']));
  $data['keywords'] = implode(', ', $keywords);

  return $data;
}

function simpleseo_node_view($node, $view_mode, $langcode) {
  if  ($view_mode == 'full') {
    $metaData = simpleseo_get_meta_data($node->nid);
    
    if ($metaData->description) {
      $metaTags['meta.description'] = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'name' => 'description',
          'content' => $metaData->description
        )
      );
    }
    
    if ($metaData->keywords) {
      $keywords = explode("\r\n", $metaData->keywords);
      $keywords = implode(', ', $keywords);
    
      $metaTags['meta.keywords'] = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'name' => 'keywords',
          'content' => $keywords
        )
      );  
    }
    
    foreach ($metaTags as $key => $val) {
      drupal_add_html_head($val, $key);
    }  
  }
}

